export function instagramProfile(value:string){const u=new URL(value);if(!['instagram.com','www.instagram.com'].includes(u.hostname)||u.protocol!=='https:'||u.username||u.password)throw Error('Use a public HTTPS Instagram profile URL.');const parts=u.pathname.split('/').filter(Boolean);if(parts.length!==1||! /^[a-zA-Z0-9._]{1,30}$/.test(parts[0])||['p','reel','reels','explore','accounts','stories'].includes(parts[0].toLowerCase()))throw Error('Enter an Instagram profile URL, not a post or login URL.');return parts[0]}
const count=(value:unknown)=>value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))&&Number(value)>=0?Number(value):null;
export function instagramRows(items:any[],source:any,runId:string){
 const collected_at=new Date().toISOString();const rows=[];
 for(const item of items){if(item.error||item.errorDescription)continue;const external_id=String(item.id||item.shortCode||'');if(!external_id)continue;let url=item.url||item.postUrl||(item.shortCode?`https://www.instagram.com/p/${item.shortCode}/`:null);try{const u=new URL(url);if(!['instagram.com','www.instagram.com'].includes(u.hostname)||u.protocol!=='https:')continue;url=u.href}catch{continue}
 const caption=String(item.caption||'').slice(0,30000),date=new Date(item.timestamp||item.takenAt||'');const hashtags=(Array.isArray(item.hashtags)?item.hashtags:caption.match(/#[\p{L}\p{N}_]+/gu)||[]).map((x:any)=>String(x).replace(/^#/,''));
 const type=String(item.type||'').toLowerCase(),content_type=type==='sidecar'||Array.isArray(item.childPosts)&&item.childPosts.length?'carousel':type==='video'?(item.productType==='clips'?'reel':'video'):'image';
 const views=count(item.videoViewCount),plays=count(item.videoPlayCount),likes=count(item.likesCount),comments=count(item.commentsCount);const engagement:any={};if(views!==null)engagement.views=views;if(plays!==null)engagement.plays=plays;if(likes!==null){engagement.likes=likes;engagement.reactions=likes}if(comments!==null)engagement.comments=comments;
 rows.push({source_id:source.id,workspace_id:source.workspace_id,external_id,content_url:url,title:caption.split('\n')[0].slice(0,150)||`${item.ownerUsername||source.name||'Instagram'} ${content_type}`,caption,body_text:caption,content_type,published_at:Number.isFinite(date.getTime())?date.toISOString():null,hashtags:[...new Set(hashtags)].slice(0,100),engagement,raw_data:{provider:'apify/instagram-post-scraper',run_id:runId,collected_at,ownerUsername:item.ownerUsername||null,shortCode:item.shortCode||null,displayUrl:item.displayUrl||null,videoUrl:item.videoUrl||null}})
 }
 return rows;
}
